-- luacheck configuration for Sink (https://github.com/lunarmodules/luacheck)
std = "lua51"
max_line_length = 140
self = false

-- Globals this addon defines or writes into.
globals = {
    "SinkDB",
    "SinkMapPinMixin",
    "SLASH_SINK1",
    "SlashCmdList",
    "Sink_OnAddonCompartmentClick",
    "StaticPopupDialogs",
}

-- WoW API this addon reads.
read_globals = {
    -- frames and widgets
    "ContainerFrameCombinedBags",
    "CreateFrame",
    "GameTooltip",
    "Minimap",
    "UIErrorsFrame",
    "UIParent",
    "WorldMapFrame",
    -- namespaces and mixins
    "C_AddOns",
    "GetMoneyString",
    "GetFactionInfoByID",
    "GetTrainerServiceSkillReq",
    "GetMoney",
    "GetTrainerServiceCost",
    "GetTaxiMapID",
    "C_TaxiMap",
    "C_Traits",
    "C_ClassTalents",
    "C_Container",
    "C_Item",
    "C_Map",
    "C_NamePlate",
    "C_Minimap",
    "C_QuestLog",
    "C_Reputation",
    "C_SkillInfo",
    "C_Spell",
    "C_SpellBook",
    "C_Timer",
    "C_TooltipInfo",
    "CampaignQuestObjectiveTracker",
    "QuestObjectiveTracker",
    "Enum",
    "EventRegistry",
    "MapCanvasDataProviderMixin",
    "MapCanvasPinMixin",
    "Menu",
    "MenuUtil",
    "MinimalSliderWithSteppersMixin",
    "TooltipDataProcessor",
    -- functions
    "ButtonFrameTemplate_HideAttic",
    "ButtonFrameTemplate_HideButtonBar",
    "ButtonFrameTemplate_HidePortrait",
    "ClearCursor",
    "GetRaidTargetIndex",
    "SetRaidTarget",
    "UnitIsDead",
    "HandleModifiedItemClick",
    "CreateFromMixins",
    "CreateVector2D",
    "CursorHasItem",
    "DeleteCursorItem",
    "GetAddOnMetadata",
    "GetGameMessageInfo",
    "GetInstanceInfo",
    "GetMerchantItemID",
    "GetMerchantItemLink",
    "GetMerchantNumItems",
    "GetNumTrainerServices",
    "GetRealmName",
    "GetSubZoneText",
    "GetTime",
    "GetTrainerServiceInfo",
    "GetTrainerServiceSkillLine",
    "GetZoneText",
    "InCombatLockdown",
    "IsPlayerSpell",
    "IsTradeskillTrainer",
    "IsSpellKnown",
    "StaticPopup_Show",
    "ShowUIPanel",
    "UnitClass",
    "UnitExists",
    "UnitFactionGroup",
    "UnitGUID",
    "UnitLevel",
    "UnitName",
    "canaccessvalue",
    "hooksecurefunc",
    "issecretvalue",
    "PanelTemplates_SetNumTabs",
    "PanelTemplates_SetTab",
    "PanelTemplates_TabResize",
    "RequestTimePlayed",
    "strsplit",
    "wipe",
    -- constants and global strings
    "BACKPACK_CONTAINER",
    "BLACK_LISTED_MESSAGE_TYPES",
    "CLOSE",
    "DELETE",
    "ERR_NEWTAXIPATH",
    "ITEM_SPELL_KNOWN",
    "NUM_BAG_SLOTS",
    "NUM_CHAT_WINDOWS",
    "NUM_CONTAINER_FRAMES",
    "NUM_TOTAL_EQUIPPED_BAG_SLOTS",
    "NORMAL_FONT_COLOR_CODE",
    "GetQuestDifficultyColor",
    "GetQuestGreenRange",
    "UnitQuestTrivialLevelRange",
    "UISpecialFrames",
    "UNIT_LEVEL_TEMPLATE",
}
